def shop_name():
    print("\n")
    print("\t\t\t\t\tWelcome to Laptop Shop")
    print("\n")
    print("\t\t\t\tThapathali, Kathmandu | 01-456790")
    print("\n")
    print("-----------------------------------------------------------------------------------------------------------------")
    print("\t\t\t\tHello, welcome to our shop")
    print("\n")
def laptop_table():
    print("-------------------------------------------------------------------------------------------------------------------")
    print("S.N. \tLaptop Name\t\tCompanyName\t\tProcessor\t\t\tRAM\t\t\tGPU\t\t\t\t\tPrice\t\tStock")
    print("-------------------------------------------------------------------------------------------------------------------")
    file = open("laptop.txt", "r")
    a = 1
    for line in file:
        print(a, "\t\t" + line.replace(",", "\t\t"))
        a = a + 1
    print("-------------------------------------------------------------------------------------------------------------------")
    file.close()
    print("\n")
def order_billing(customer_name, datetime, customer_phone, customer_address, laptop_name, laptop_brand, actual_price, price_vat):
    current = datetime.datetime.now()
    date_time = current.strftime("%m/%d/%Y, %H:%M:%S")
    f = open(f'{customer_name}.txt', 'w')
    print(f"Date:{date_time}\n")
    print(f"Customer Name:{customer_name}\n")
    print(f"Customer PhoneNumber:{customer_phone}\n")
    print(f"Customer Address:{customer_address}\n")
    print(f"Laptop Name:{laptop_name}\n")
    print(f"Laptop Brand:{laptop_brand}\n")
    print(f"Price before Shipping :${actual_price}\n")
    print(f"Price with Vat:${price_vat}\n")
    f.write(f"Date:{date_time}\n")
    f.write(f"Name: {customer_name}\n")
    f.write(f"PhoneNumber: {customer_phone}\n")
    f.write(f"Address:{customer_address}\n")
    f.write(f"Name: {laptop_name}\n")
    f.write(f"Laptop Brand: {laptop_brand}\n")
    f.write(f"Price before Shipping :${actual_price}\n")
    f.write(f"Price with Vat:${price_vat}\n")
    f.close()
def buy_billing(datetime, customer_name, customer_phone, customer_address, laptop_name, laptop_brand, actual_price, ship, with_shipping):
    current = datetime.datetime.now()
    date_time = current.strftime("%m/%d/%Y, %H:%M:%S")
    f = open(f'{customer_name}.txt', 'w')
    print(f"Date:{date_time}\n")
    print(f"Customer Name:{customer_name}\n")
    print(f"Customer PhoneNumber:{customer_phone}\n")
    print(f"Customer Address:{customer_address}\n")
    print(f"Laptop Name:{laptop_name}\n")
    print(f"Laptop Brand:{laptop_brand}\n")
    print(f"Price before Shipping :${actual_price}\n")
    if ship == "y":
        print(f"Price with ShippingCost:${with_shipping}\n")
    else:
        print("Your product was not shipped")
        f.write(f"Date:{date_time}\n")
        f.write(f"Name: {customer_name}\n")
        f.write(f"PhoneNumber: {customer_phone}\n")
        f.write(f"Address:{customer_address}")
        f.write(f"Name: {laptop_name}\n")
        f.write(f"Laptop Brand: {laptop_brand}\n")
        f.write(f"Price before Shipping :${actual_price}\n")
